#pragma once

// ml_classifier.h
// Auto-generated by train_model.py. 
// Do not manually modify. Replace via `python ml/training/train_model.py`.

/**
 * Exact function signature required by the firmware pipeline.
 * Features:
 *   - ttc_basic (s)
 *   - ttc_ext (s)
 *   - v_host (m/s)
 *   - v_closing (m/s)
 *   - a_decel (m/s^2)
 *   - road_flag (0=dry, 1=wet, 2=gravel, 3=ice)
 */
inline int classifyRiskML(float ttc_basic, float ttc_ext, float v_host, float v_closing, float a_decel, float road_flag) {

    if (ttc_basic <= 1.661f) {
        if (ttc_basic <= 1.321f) {
            return 2; // Class 2
        } else {
            return 2; // Class 2
        }
    } else {
        if (ttc_basic <= 3.572f) {
            if (ttc_basic <= 2.936f) {
                return 1; // Class 1
            } else {
                return 1; // Class 1
            }
        } else {
            return 0; // Class 0
        }
    }
    return 0;
}