"""Compatibility exports for project configuration.

This package name collides with imports like `from config import ...`.
Re-export symbols from `src.config` so existing imports resolve reliably.
"""

from src.config import (
    BASE_DIR,
    ROOT_DIR,
    MODEL_PATH,
    DATA_PATH,
    LOG_DIR,
    CONFIG_FILE,
    DATASET_DIR,
    VALIDATION_DIR,
    REPORTS_DIR,
    TELEMETRY_FIELDS,
    TELEMETRY_FIELD_COUNT,
    SESSION_CSV_COLUMNS,
    RISK_THRESHOLDS,
    RISK_LABELS,
    RISK_INVERSE,
    RISK_COLORS,
    DASHBOARD_CONFIG,
    SERIAL_CONFIG,
    SIMULATOR_CONFIG,
    ALERT_CONFIG,
    ANOMALY_CONFIG,
    PHYSICS_CONFIG,
    VALIDATION_CONFIG,
    LOGGING_CONFIG,
    get_risk_class,
    get_risk_label,
    load_config_from_file,
    save_config_to_file,
)

__all__ = [
    "BASE_DIR",
    "ROOT_DIR",
    "MODEL_PATH",
    "DATA_PATH",
    "LOG_DIR",
    "CONFIG_FILE",
    "DATASET_DIR",
    "VALIDATION_DIR",
    "REPORTS_DIR",
    "TELEMETRY_FIELDS",
    "TELEMETRY_FIELD_COUNT",
    "SESSION_CSV_COLUMNS",
    "RISK_THRESHOLDS",
    "RISK_LABELS",
    "RISK_INVERSE",
    "RISK_COLORS",
    "DASHBOARD_CONFIG",
    "SERIAL_CONFIG",
    "SIMULATOR_CONFIG",
    "ALERT_CONFIG",
    "ANOMALY_CONFIG",
    "PHYSICS_CONFIG",
    "VALIDATION_CONFIG",
    "LOGGING_CONFIG",
    "get_risk_class",
    "get_risk_label",
    "load_config_from_file",
    "save_config_to_file",
]
