% MATLAB Validation Script for TTC Telemetry Data
% This script reads a CSV file generated by the system and validates 
% the underlying TTC calculations and thresholds.

clear; clc;

% Load dataset
filename = 'outputs/synthetic_ttc_validation.csv';
if exist(filename, 'file')
    data = readtable(filename);
else
    disp('Validation dataset not found.');
    return;
end

% Validate distances
invalid_distances = find(data.distance_cm < 0);
if ~isempty(invalid_distances)
    fprintf('Warning: Found %d negative distances.\n', length(invalid_distances));
end

% Validate TTC calculations
calculated_ttc = (max(data.distance_cm, 0) / 100.0) ./ max(data.speed_kmh / 3.6, 0.1);
ttc_error = abs(data.ttc_basic - calculated_ttc);
max_error = max(ttc_error(~isinf(calculated_ttc) & ~isinf(data.ttc_basic)));
fprintf('Max error in TTC basic calculation: %.4f seconds\n', max_error);

% Plot results
figure;
plot(data.timestamp_ms, data.distance_cm / 100.0, 'b-', 'LineWidth', 1.5);
hold on;
plot(data.timestamp_ms, data.speed_kmh, 'r--', 'LineWidth', 1.5);
plot(data.timestamp_ms, data.ttc_basic, 'm-', 'LineWidth', 1.2);
legend('Distance (m)', 'Speed (km/h)', 'TTC Basic (s)');
xlabel('Time (ms)');
ylabel('Value');
title('Telemetry Validation');
grid on;

disp('MATLAB validation completed successfully.');
