"""
train_model.py - ML Model Training & C++ Code Generation

Niroop's Capstone Project

PURPOSE:
This script trains two models:
1. Random Forest (cloud/dashboard version) - high accuracy, complex
2. Decision Tree (edge firmware version) - simpler, runs on ESP32

LEARNING JOURNEY:
Week 1: Started with logistic regression - accuracy 70% (too simple!)
Week 2: Tried SVM - works but slow to deploy to firmware
Week 3: Read about Random Forests - way better! 88% accuracy
Week 4: Realized we need Decision Tree for firmware (not enough memory for RF)
Week 5: Implemented tree2C conversion - magical moment when it worked!

ML TRAINING NOTES:
Training Data:
    - Synthetic kinematic scenarios (no real collisions - too rare!)
    - Features: TTC basic, TTC extended, vehicle speed, closing velocity, deceleration, road condition
    - Labels: SAFE(0), WARNING(1), CRITICAL(2)
    - Size: ~5000 samples (generated by synthetic_validation_dataset.py)

Model Evolution:
    ✗ Attempt 1: Logistic Regression - too simple (70% accuracy)
    ✗ Attempt 2: SVM - good but deploy-unfriendly
    ✓ Attempt 3: Random Forest (server) + Decision Tree (edge)

Random Forest (Dashboard):
    - n_estimators=50 (50 trees = good diversity)
    - max_depth=5 (prevent overfitting)
    - 5-fold CV accuracy: ~88-92% (varies with synthetic data)
    - Saved as .pkl file, loaded by dashboard.py

Decision Tree (Firmware):
    - max_depth=4 (fits in ESP32 memory + fast inference)
    - min_samples_leaf=5 (avoid overfitting to noise)
    - Auto-converted to C++ if-else chain
    - Inference time: <1ms on ESP32 (fast enough!)

C++ GENERATION INSIGHTS:
    - Nested if-else tree structure (inefficient but works!)
    - Each node becomes: if (feature <= threshold)
    - Leaf nodes return class (0/1/2)
    - Example: 4-depth tree → ~30 lines of C++ code
    - Could optimize with lookup tables (TODO)

TESTING PROCESS:
    1. Generate synthetic dataset
    2. Train models (takes ~5 seconds)
    3. Cross-validate (ensure not overfitting)
    4. Export Random Forest to pickle
    5. Generate C++ header from Decision Tree
    6. Commit and rebuild firmware

OBSERVATIONS:
    - More training data = better accuracy (validation gap shrinks)
    - Road conditions affect classification heavily
        (ice scenarios often misclassified as dry)
    - Threshold tuning critical (where safe/warning boundary?)

FUTURE IMPROVEMENTS:
    TODO: Online learning (update model with real collision data)
    TODO: Model versioning (track which version used for which test)
    TODO: Automated retraining pipeline (weekly)
    TODO: Compare models: confidence score from RF vs simple DT rules

Run this script with:
    python ml/training/train_model.py

Outputs:
    - MODELS/ml_model.pkl (Random Forest for dashboard)
    - firmware/ml_classifier/ml_classifier.h (Decision Tree for ESP32)
"""

import os
import sys
from typing import List
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report
import joblib

BASE_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(BASE_DIR))

from src.config import MODEL_PATH, DATASET_DIR  # noqa: E402

CSV_PATH = DATASET_DIR / "synthetic_ttc_validation.csv"
HEADER_PATH = BASE_DIR / "firmware" / "ml_classifier" / "ml_classifier.h"


def _tree_to_c(tree: DecisionTreeClassifier, feature_names: List[str]) -> str:
    """
    Generate C++ code representation of decision tree classifier.

    Converts a trained scikit-learn DecisionTreeClassifier into executable C++ code
    suitable for deployment on embedded systems (ESP32). The generated code is a
    nested if-else structure that mirrors the tree's decision nodes.

    The output is a complete C++ header file containing an inline function
    'classifyRiskML' that accepts feature values and returns a risk class integer.

    Args:
        tree: Trained scikit-learn DecisionTreeClassifier with learned decision rules
        feature_names: List of feature column names in the same order as training data.
                      Expected: ['ttc_basic', 'ttc_ext', 'v_host', 'v_closing',
                                'a_decel', 'road_flag']

    Returns:
        String containing complete C++ header file code that implements the decision
        tree as a series of nested if-else statements. Each leaf node returns a risk
        class integer (0=SAFE, 1=WARNING, 2=CRITICAL).

    Example:
        >>> dt = DecisionTreeClassifier(max_depth=4)
        >>> dt.fit(X_train, y_train)
        >>> cpp_code = _tree_to_c(dt, ['ttc_basic', 'ttc_ext', 'v_host'])
        >>> # cpp_code contains: inline int classifyRiskML(...) { if (...) ... }
    """
    tree_ = tree.tree_
    feature_name = [
        feature_names[i] if i != -2 else "undefined!" for i in tree_.feature
    ]

    header = """#pragma once

// ml_classifier.h
// Auto-generated by train_model.py.
// Do not manually modify. Replace via `python ml/training/train_model.py`.

/**
 * Exact function signature required by the firmware pipeline.
 * Features:
 *   - ttc_basic (s)
 *   - ttc_ext (s)
 *   - v_host (m/s)
 *   - v_closing (m/s)
 *   - a_decel (m/s^2)
 *   - road_flag (0=dry, 1=wet, 2=gravel, 3=ice)
 */
inline int classifyRiskML(float ttc_basic, float ttc_ext, float v_host, float v_closing, float a_decel, float road_flag) {
"""

    code = [header]

    def recurse(node: int, depth: int) -> None:
        """Recursively traverse tree nodes and generate C++ if-else code."""
        indent = "    " * depth
        if tree_.feature[node] != -2:
            name = feature_name[node]
            threshold = tree_.threshold[node]
            code.append("{}if ({} <= {:.3f}f) {{".format(indent, name, threshold))
            recurse(tree_.children_left[node], depth + 1)
            code.append("{}}} else {{".format(indent))
            recurse(tree_.children_right[node], depth + 1)
            code.append("{}}}".format(indent))
        else:
            cls = np.argmax(tree_.value[node][0])
            code.append("{}return {}; // Class {}".format(indent, cls, cls))

    recurse(0, 1)

    code.append("    return 0;\n}")
    return "\n".join(code)


def main() -> None:
    """
    Main training pipeline for TTC risk classification models.

    Performs the following steps:
    1. Loads synthetic validation dataset from CSV
    2. Trains Random Forest classifier for cloud/dashboard deployment (high accuracy)
    3. Trains Decision Tree classifier for edge/firmware deployment (memory-efficient)
    4. Evaluates both models with cross-validation and classification metrics
    5. Exports Random Forest to pickle file (MODELS/ml_model.pkl)
    6. Generates C++ header from Decision Tree (firmware/ml_classifier/ml_classifier.h)

    Features used:
        - ttc_basic: Basic time-to-collision (seconds)
        - ttc_ext: Extended TTC with deceleration (seconds)
        - v_host: Host vehicle speed (m/s)
        - v_closing: Closing velocity (m/s)
        - a_decel: Deceleration rate (m/s²)
        - road_flag: Road condition (0=dry, 1=wet, 2=gravel, 3=ice)

    Target classes:
        - 0: SAFE
        - 1: WARNING
        - 2: CRITICAL

    Exits with code 1 if dataset is not found.

    Returns:
        None. Outputs are written to files and printed to console.
    """
    if not CSV_PATH.exists():
        print(f"Error: dataset not found at {CSV_PATH}")
        print("Run `python src/synthetic_validation_dataset.py` first.")
        sys.exit(1)

    print("Loading dataset...")
    features = ["ttc_basic", "ttc_ext", "v_host", "v_closing", "a_decel", "road_flag"]
    target = "ground_truth_risk_class"
    required_columns = features + [target]

    df = pd.read_csv(CSV_PATH)
    df = df.dropna(subset=required_columns)

    X = df[features]
    y = df[target]

    print(f"Dataset shape: {X.shape}")

    # Random forest for server
    print("\nTraining Random Forest for cloud/dashboard implementation...")
    rf = RandomForestClassifier(n_estimators=50, max_depth=5, random_state=42)
    scores = cross_val_score(rf, X, y, cv=5)
    print(f"RF CV Accuracy: {np.mean(scores)*100:.2f}%")

    rf.fit(X, y)
    rf.feature_names_in_ = np.array(features)

    os.makedirs(MODEL_PATH.parent, exist_ok=True)
    joblib.dump(rf, MODEL_PATH)
    print(f"Saved Random Forest to {MODEL_PATH}")

    # Decision tree for edge deployment
    print("\nTraining Decision Tree for edge deployment...")
    dt = DecisionTreeClassifier(max_depth=4, min_samples_leaf=5, random_state=42)
    dt.fit(X, y)
    dt_acc = dt.score(X, y)
    print(f"DT Accuracy: {dt_acc*100:.2f}%")

    y_pred = dt.predict(X)
    print("\nClassification Report (Edge Model):")
    print(classification_report(y, y_pred))

    print("\nGenerating C++ header...")
    cpp_code = _tree_to_c(dt, features)

    os.makedirs(HEADER_PATH.parent, exist_ok=True)
    with open(HEADER_PATH, "w") as f:
        f.write(cpp_code)
    print(f"Exported C++ Decision Tree to {HEADER_PATH}")


if __name__ == "__main__":
    main()
