import os
import sys
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import joblib

BASE_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(BASE_DIR))

from src.config import MODEL_PATH, DATASET_DIR

CSV_PATH = DATASET_DIR / "synthetic_ttc_validation.csv"
HEADER_PATH = BASE_DIR / "firmware" / "ml_classifier" / "ml_classifier.h"

def _tree_to_c(tree, feature_names):
    """Generate C++ string representation of decision tree"""
    tree_ = tree.tree_
    feature_name = [
        feature_names[i] if i != -2 else "undefined!"
        for i in tree_.feature
    ]

    header = '''#pragma once

// ml_classifier.h
// Auto-generated by train_model.py. 
// Do not manually modify. Replace via `python ml/training/train_model.py`.

/**
 * Exact function signature required by the firmware pipeline.
 * Features:
 *   - ttc_basic (s)
 *   - ttc_ext (s)
 *   - v_host (m/s)
 *   - v_closing (m/s)
 *   - a_decel (m/s^2)
 *   - road_flag (0=dry, 1=wet, 2=gravel, 3=ice)
 */
inline int classifyRiskML(float ttc_basic, float ttc_ext, float v_host, float v_closing, float a_decel, float road_flag) {
'''
    
    code = [header]

    def recurse(node, depth):
        indent = "    " * depth
        if tree_.feature[node] != -2:
            name = feature_name[node]
            threshold = tree_.threshold[node]
            code.append("{}if ({} <= {:.3f}f) {{".format(indent, name, threshold))
            recurse(tree_.children_left[node], depth + 1)
            code.append("{}}} else {{".format(indent))
            recurse(tree_.children_right[node], depth + 1)
            code.append("{}}}".format(indent))
        else:
            cls = np.argmax(tree_.value[node][0])
            code.append("{}return {}; // Class {}".format(indent, cls, cls))

    recurse(0, 1)
    
    code.append('    return 0;\n}')
    return "\n".join(code)

def main():
    if not CSV_PATH.exists():
        print(f"Error: dataset not found at {CSV_PATH}")
        print("Run `python src/synthetic_validation_dataset.py` first.")
        sys.exit(1)

    print("Loading dataset...")
    features = ["ttc_basic", "ttc_ext", "v_host", "v_closing", "a_decel", "road_flag"]
    target = "ground_truth_risk_class"
    required_columns = features + [target]

    df = pd.read_csv(CSV_PATH)
    df = df.dropna(subset=required_columns)

    X = df[features]
    y = df[target]

    print(f"Dataset shape: {X.shape}")

    # Random forest for server
    print("\nTraining Random Forest for cloud/dashboard implementation...")
    rf = RandomForestClassifier(n_estimators=50, max_depth=5, random_state=42)
    scores = cross_val_score(rf, X, y, cv=5)
    print(f"RF CV Accuracy: {np.mean(scores)*100:.2f}%")
    
    rf.fit(X, y)
    rf.feature_names_in_ = np.array(features)
    
    os.makedirs(MODEL_PATH.parent, exist_ok=True)
    joblib.dump(rf, MODEL_PATH)
    print(f"Saved Random Forest to {MODEL_PATH}")

    # Decision tree for edge deployment
    print("\nTraining Decision Tree for edge deployment...")
    dt = DecisionTreeClassifier(max_depth=4, min_samples_leaf=5, random_state=42)
    dt.fit(X, y)
    dt_acc = dt.score(X, y)
    print(f"DT Accuracy: {dt_acc*100:.2f}%")
    
    y_pred = dt.predict(X)
    print("\nClassification Report (Edge Model):")
    print(classification_report(y, y_pred))

    print("\nGenerating C++ header...")
    cpp_code = _tree_to_c(dt, features)
    
    os.makedirs(HEADER_PATH.parent, exist_ok=True)
    with open(HEADER_PATH, "w") as f:
        f.write(cpp_code)
    print(f"Exported C++ Decision Tree to {HEADER_PATH}")

if __name__ == "__main__":
    main()
